version: '1.0'
name: pipeline
displayName: pipeline
triggers:
  trigger: auto
  push:
    branches:
      precise:
        - master
stages:
  - name: stage-efb54805
    displayName: 打包发布
    strategy: naturally
    trigger: auto
    executor: []
    steps:
      - step: build@nodejs
        name: build_nodejs
        displayName: Nodejs 构建
        nodeVersion: 17.8.0
        commands:
          - '# 设置NPM源，提升安装速度'
          - npm config set registry https://registry.npmmirror.com
          - ''
          - '# 执行编译命令'
          - npm install && npm run build
          - ''
          - cd ./dist
          - ''
          - npm version batch
          - ''
          - npm publish
        artifacts:
          - name: BUILD_ARTIFACT
            path:
              - ./dist
        caches:
          - ~/.npm
          - ~/.yarn
        notify: []
        strategy:
          retry: '0'
